import cx_Freeze

executables = [cx_Freeze.Executable("petup.py", None, None, "PETUP")]

cx_Freeze.setup(
    name="PET UP",
    options={"build_exe": {"packages":["pygame"],
                           "include_files":["Imagens/personagem/personagem1frente.png", "Imagens/personagem/personagem2frente.png", "Imagens/personagem/personagem1frente_min.png", "Imagens/personagem/selecao.png","Imagens/Página inicial/paginainicial2.png","Imagens/Página inicial/play.png","Imagens/Primeira Fase/ensino.png","Imagens/Primeira Fase/pesquisa.png","Imagens/Primeira Fase/extensão.png","Imagens/Primeira Fase/iconefinal.png","Imagens/Primeira Fase/chao.png","Imagens/Primeira Fase/fundo123desfocado.png","Imagens/Game Over/gameover.png","Imagens/Primeira Fase/transição.png","Imagens/Segunda Fase/transiçãof2.png","Imagens/Primeira Fase/playtransição.png","Imagens/Segunda Fase/brio.png","Imagens/Segunda Fase/capacitação.png","Imagens/Segunda Fase/humildade.png","Imagens/Segunda Fase/comprometimento.png","Imagens/Segunda Fase/UNIÃO.png","Imagens/Quinta Fase/botaoexpetianos.png","Imagens/pontuaçãoobject.png","Imagens/Game Over/pontosgameover.png", "Imagens/Quinta Fase/fimdejogo.png","Imagens/Quinta Fase/botaofinal.png","Imagens/Página inicial/créditos.png","Som/Músicas/day 33.mp3","Imagens/personagem/personagem2frente_min.png","Imagens/Primeira Fase/fundo1_112.png","Som/Músicas/day 32.mp3","Som/Músicas/Rise of spirit.ogg","Imagens/Quinta Fase/personagemfinal.png","Imagens/Quinta Fase/personagem2final.png","Imagens/Primeira Fase/plataforma1.png","Imagens/Segunda Fase/plataforma2.png","Imagens/Terceira Fase/plataforma3.png","Imagens/Quarta Fase/plataforma4.png","Imagens/Segunda Fase/fundo2.png","Som/Músicas/day 43.mp3","Imagens/personagem/personagem1minespaço.png","Imagens/personagem/personagem2minespaço.png","Som/Músicas/Full of memories.ogg","Imagens/Terceira Fase/fundo3.png","Imagens/Quarta Fase/fundo 4.png","Som/Músicas/day 34.mp3","Imagens/Quarta Fase/obstáculos/COO.png","Imagens/Quarta Fase/obstáculos/SEC.png","Imagens/Quarta Fase/obstáculos/PEP.png","Imagens/Quarta Fase/obstáculos/MKT.png","Imagens/Quarta Fase/obstáculos/EVT.png","Imagens/Quarta Fase/obstáculos/INTERPET.png","Imagens/Quarta Fase/obstáculos/qld.png","Imagens/Quinta Fase/fundo5.png","Imagens/Quinta Fase/fundo5desfocado.png","Som/Músicas/day 10.mp3","Imagens/Segunda Fase/Fundo2desfocado.png","Imagens/Terceira Fase/Fundo3desfocado.png","Imagens/Quarta Fase/Fundo4desfocado.png",]}},
    executables = executables

    )